#!/bin/sh
# -*- sh -*-
LIBDIR=`rpm --eval "%{_libdir}"`/lksctp-tools
BINDIR=/usr/bin
LIBVER=1.0.18
export LD_PRELOAD=${LIBDIR}/libwithsctp.so.${LIBVER}
if ! ${BINDIR}/checksctp 2> /dev/null
then
    ${BINDIR}/checksctp;
    exit 1;
fi

exec "$@"
